name: Build Unsigned IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Strip iOS Capabilities safely
        shell: bash
        run: |
          echo "Stripping entitlements..."
      
          find . -name "*.entitlements" | while read file; do
            echo "Cleaning $file"
            printf '%s\n' '<?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
          </dict>
          </plist>' > "$file"
              done
          
              echo "Capabilities stripped"



      - name: Build app (no signing)
        run: |
          xcodebuild \
            -workspace "Nostalgic Music Player.xcworkspace" \
            -scheme "Nostalgic Music Player" \
            -sdk iphoneos \
            -configuration Release \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO
            CODE_SIGNING_REQUIRED=NO
            CODE_SIGN_IDENTITY=""
            DEVELOPMENT_TEAM=""
            PROVISIONING_PROFILE_SPECIFIER=""
            ENABLE_BITCODE=NO

      - name: Create Payload
        run: |
          mkdir -p Payload
          cp -R build/Build/Products/Release-iphoneos/*.app Payload/

      - name: Zip IPA
        run: |
          zip -r NostalgicMusicPlayer.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: NostalgicMusicPlayer-IPA
          path: NostalgicMusicPlayer.ipa
